name: xilowidgets
description: Xilogism widgets
repository: https://github.com/MyGithubAccount/slidablepanel/src/flutter/slidablepanel
version: 0.1.0
homepage: https://github.com/MyGithubAccount/slidablepanel

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.26.0
  flutter_slidable_panel:
  flutter:
    sdk: flutter
  interactive_viewer_2: ^0.0.10
  flutter_code_editor: ^0.3.3
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
